# Generated by Django 3.1.1 on 2020-12-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201202_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=1333)),
            ],
        ),
    ]
